APollPoll.Web/Controllers/AccountController.cs
using APollPoll.Services.Accounts.Models;
using APollPoll.Web.Authorization;
using Newtonsoft.Json;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Net;
using System.Net.Mail;
using System.Web;
using System.Web.Mvc;
using System.Web.Security;

namespace APollPoll.Web.Controllers
{
    public class AccountController : Controller
    {
        // GET: Account
        public ActionResult Index()
        {
            return View();
        }

        [HttpGet]
        public ActionResult Login(string returnUrl = "")
        {
            ViewBag.ReturnUrl = returnUrl;
            return View();
        }

        [HttpPost]
        public ActionResult Login(LoginRequest model, string returnUrl = "")
        {
            if (ModelState.IsValid && Membership.ValidateUser(model.Email, model.Password))
            {
                var user = (AuthMembershipUser)Membership.GetUser(model.Email, false);
                if (user != null)
                {
                    var userModel = new AuthSerializeModel()
                    {
                        Id = user.Id,
                        FirstName = user.FirstName,
                        LastName = user.LastName,
                        Role = user.Role
                    };

                    var userData = JsonConvert.SerializeObject(userModel);
                    var authTicket = new FormsAuthenticationTicket(1, model.Email, DateTime.Now, DateTime.Now.AddMinutes(15), false, userData);
                    var encryptedTicket = FormsAuthentication.Encrypt(authTicket);
                    var cookie = new HttpCookie("AuthCookie", encryptedTicket);
                    Response.Cookies.Add(cookie);
                }

                if (Url.IsLocalUrl(returnUrl))
                {
                    return Redirect(returnUrl);
                }
                else
                {
                    return RedirectToAction("Index", "Home");
                }
            }
            ModelState.AddModelError("", "User or Password is invalid.");
            return View(model);
        }

        public ActionResult LogOut()
        {
            Response.Cookies.Add(new HttpCookie("AuthCookie", "")
            {
                Expires = DateTime.Now.AddYears(-1)
            });

            FormsAuthentication.SignOut();
            return RedirectToAction("Index", "Home");
        }
    }
}

APollPoll.Web/Controllers/HomeController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace APollPoll.Web.Controllers
{
    public class HomeController : Controller
    {
        public ActionResult Index()
        {
            return View();
        }
    }
}

APollPoll.Web/Controllers/OptionController.cs
using APollPoll.Services.Options.Models;
using APollPoll.Services.Options.Service;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using System.Web;
using System.Web.Mvc;

namespace APollPoll.Web.Controllers
{
    public class OptionController : Controller
    {
        private readonly IOptionService _service;
        public OptionController(IOptionService service)
        {
            _service = service;
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<ActionResult> Add(OptionCreate model)
        {
            if (!ModelState.IsValid)
                return View(ModelState);

            if (await _service.CreateAsync(model) == 1)
                return RedirectToAction("Details", "Question", new { id = model.QuestionId });

            ModelState.AddModelError("Save Failed", "Could not save the answer.");
            return View(model);
        }


    }
}

APollPoll.Web/Controllers/QuestionController.cs
using APollPoll.Services.Questions.Models;
using APollPoll.Services.Questions.Service;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using System.Web;
using System.Web.Mvc;

namespace APollPoll.Web.Controllers
{
    public class QuestionController : Controller
    {
        private readonly IQuestionService _service;
        public QuestionController(IQuestionService service)
        {
            _service = service;
        }

        [HttpGet]
        public async Task<ActionResult> Index()
        {
            var questions = await _service.GetAllAsync();
            return View(questions);
        }

        [HttpGet]
        public ActionResult Create()
        {
            return View(new QuestionCreate());
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<ActionResult> Create(QuestionCreate model)
        {
            if (!ModelState.IsValid)
                return View(ModelState);

            model.Options = model.Options.Where(o => o.IsValid).ToList();

            if (await _service.CreateAsync(model) == 1 + model.Options.Count)
                return RedirectToAction(nameof(Index));

            ModelState.AddModelError("Save Failed", "Could not save the question.");
            return View(model);
        }

        [HttpGet]
        public async Task<ActionResult> Details(int? id)
        {
            if (!id.HasValue)
                return HttpNotFound();

            var detail = await _service.GetByIdAsync(id.Value);

            if (detail is null)
                return HttpNotFound();

            return View(detail);
        }
    }
}

APollPoll.Web/Views/Home/Index.cshtml
@{
    ViewBag.Title = "Home Page";
}


<div class="jumbotron">
    <h1 class="text-center">A Poll Poll</h1>
    <p class="lead text-center">A Poll Poll, or APP for short, is an application that allows you to help create some of the great polls of the century. You want good polls? Well then give good questions! We'll then turn around and use these questions in the class polls. This is your chance to start great things!</p>
    <p class="text-center">That said, this can easily be shut down, so don't abuse it. :)</p>
    <p class="text-center"><a href="/Question" class="btn btn-danger btn-lg">Do your part &raquo;</a></p>
</div>
@if (User.Identity.IsAuthenticated)
{
    <a href="https://www.youtube.com/watch?v=Hm3JodBR-vs" target="_blank" class="text-center">Hi! You're logged in, isn't that neat. How neat is that? That's pretty neat. </a>
}

APollPoll.Web/Views/Option/_AddPartial.cshtml
@model APollPoll.Services.Options.Models.OptionCreate

@{
    ViewBag.Modal = "OptionCreateModal";
    ViewBag.Btn = "OptionCreateBtn";
    ViewBag.Btn2 = "ModalBtn2";
}

<button id="@Html.Raw(ViewBag.Btn)" type="button" class="btn btn-danger">
    Add Answer
</button>

<div class="modal fade" tabindex="-1" id="@Html.Raw(ViewBag.Modal)" data-keyboard="true" data-backdrop="static">
    <div class="modal-dialog modal-lg">
        <div class="modal-content">
            <div class="modal-header">
                <button type="button" class="close" data-dismiss="modal">
                    ×
                </button>
                <h4 class="pull-left">Create Answer</h4>
            </div>
            <div class="modal-body">
                @using (Html.BeginForm("Add", "Option", FormMethod.Post))
                {
                    @Html.AntiForgeryToken()
                    @Html.HiddenFor(model => model.QuestionId)

                    <div class="form-horizontal">
                        @Html.ValidationSummary(true, "", new { @class = "text-danger" })
                        <div class="form-group">
                            <div class="col-md-12">
                                @Html.TextAreaFor(model => model.Text, new { @class = "form-control", style = "min-width: 100%; width: 100%;" })
                                @Html.ValidationMessageFor(model => model.Text, "", new { @class = "text-danger" })
                            </div>
                        </div>

                        <div class="form-group">
                            <div class="col-md-12 text-right">
                                <input type="submit" value="Submit" class="btn btn-danger" />
                                <input type="button" value="Cancel" class="btn btn-dark" data-dismiss="modal" />
                            </div>
                        </div>
                    </div>
                }
            </div>
        </div>
    </div>
</div>

<script src="https://ajax.googleapis.com/ajax/libs/jquery/1.11.3/jquery.min.js"></script>
<script type="text/javascript">
    $(document).ready(function () {
        $(@Html.Raw(ViewBag.Btn)).click(function () {
            $(@Html.Raw(ViewBag.Modal)).modal('show');
        });
    });
</script>

APollPoll.Web/Views/Question/Create.cshtml
@using APollPoll.Services.Questions.Models;
@using APollPoll.Services.Options.Models;
@model QuestionCreate

@{
    ViewBag.Title = "Create";
}

<div class="col-md-8" style="margin: auto;">
    <h2 class="text-center">Create New Question</h2>
</div>
<hr />
<div class="col-md-12">

    @using (Html.BeginForm())
    {
        @Html.AntiForgeryToken()

        <div class="form-horizontal">
            @Html.ValidationSummary(true, "", new { @class = "text-danger" })
            <div class="form-group">
                @Html.LabelFor(model => model.Title, htmlAttributes: new { @class = "control-label col-md-2" })
                <div class="col-md-10">
                    @Html.TextAreaFor(model => model.Title, new { @class = "form-control", style = "min-width: 100%; width: 100%;" })
                    @Html.ValidationMessageFor(model => model.Title, "", new { @class = "text-danger" })
                </div>
            </div>

            <div class="form-group">
                @Html.LabelFor(model => model.IsMultipleChoice, htmlAttributes: new { @class = "control-label col-md-2" })
                <div class="col-md-10">
                    <div class="checkbox">
                        @Html.EditorFor(model => model.IsMultipleChoice)
                        @Html.ValidationMessageFor(model => model.IsMultipleChoice, "", new { @class = "text-danger" })
                    </div>
                </div>
            </div>

            <div class="text-center">
                <input id="btnAddOption" class="btn btn-default" style="margin-bottom: 5px;" type="button" onclick="addOptionDiv()" value="Add New Option" />
            </div>
            <div id="optionTable" class="text-center">
            </div>

            <div class="form-group">
                <div class="text-center">
                    <input type="submit" value="Submit Question" class="btn btn-danger" />
                    @Html.ActionLink("Back to List", "Index", null, new { @class = "btn btn-dark" })
                </div>
            </div>
        </div>
    }
</div>

<script src="~/Scripts/addOption.js"></script>
<script>
function addOptionDiv() {
    @{Model.Options.Add(new OptionCreate());}
        addOption("#optionTable");
    }
</script>

@section Scripts {
    @Scripts.Render("~/bundles/jqueryval")
}

APollPoll.Web/Views/Question/Details.cshtml
@model APollPoll.Services.Questions.Models.QuestionDetail

@{
    ViewBag.Title = "Details";
}

<h1>
    @Model.Title
    <span style="font-style: italic; font-size: 2.4rem;">@(Model.IsMultipleChoice?"Multiple":"Single") Answer Choice</span>
</h1>

@if (Model.Options.Count > 0)
{
    <div class="row" style="margin-left: 0;">
        @foreach (var item in Model.Options)
        {
            <div class="col-md-4">
                <div class="speech-bubble">
                    @Html.DisplayFor(modelItem => item.Text)
                </div>
            </div>
        }
    </div>
}
else
{
    <div style="position: relative; min-height: 14em; text-align: center;">
        <h4 class="center">
            This question currently has no possibly answers. This means that the person who added this question didn't even add an option. They should be ashamed. Go ahead and be better than them: <a id="ModalBtn2">Add a new option now</a>!
        </h4>
    </div>

    <script src="https://ajax.googleapis.com/ajax/libs/jquery/1.11.3/jquery.min.js"></script>
    <script type="text/javascript">
    $(document).ready(function () {
        $(@Html.Raw("ModalBtn2")).click(function () {
            $(@Html.Raw("OptionCreateModal")).modal('show');
        });
    });
    </script>
}

<div class="text-right">
    @Html.Partial("~/Views/Option/_AddPartial.cshtml", new APollPoll.Services.Options.Models.OptionCreate { QuestionId = Model.Id })
    @Html.ActionLink("Back to List", "Index", null, new { @class = "btn btn-dark" })
</div>

@section Scripts {
    @Scripts.Render("~/bundles/jqueryval")
}

APollPoll.Web/Views/Question/Index.cshtml
@model IEnumerable<APollPoll.Services.Questions.Models.QuestionListItem>

@{
    ViewBag.Title = "Questions";
}

<div class="row" style="margin-top: 15px; margin-bottom: 6px;">
    <h2 class="col-md-6" style="margin-top: 0;">
        Questions
    </h2>
    <div class="col-md-6 text-right">
        @Html.ActionLink("Create New Question", "Create", null, new { @class = "btn btn-danger" })
    </div>
</div>

<table class="table">
    <tr>
        <th>
            @Html.DisplayNameFor(model => model.Title)
        </th>
        <th style="text-align: right;">
            @Html.DisplayNameFor(model => model.OptionCount)
        </th>
        <th></th>
    </tr>

    @foreach (var item in Model)
    {
        <tr>
            <td>
                @Html.DisplayFor(modelItem => item.Title)
            </td>
            <td style="text-align: right;">
                @Html.DisplayFor(modelItem => item.OptionCount)
            </td>
            <td style="text-align: right;">
                @Html.ActionLink("See Answers", "Details", new { id = item.Id }, new { @class = "btn btn-dark" })
            </td>
        </tr>
    }

</table>

APollPoll.Web/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>@ViewBag.Title - APP</title>
    @Styles.Render("~/Content/css")
    @Scripts.Render("~/bundles/modernizr")
    <link rel="stylesheet" href="https://fonts.googleapis.com/css?family=Overpass">
</head>
<body style="height: 100vh;">
    <div class="navbar navbar-inverse navbar-fixed-top">
        <div class="container" style="padding-right: 0;">
            <div class="navbar-header">
                <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                </button>
                <a class="navbar-brand brand-logo" style="padding: 0;" href="https://elevenfifty.org/" target="_blank">
                    <img class="nav-logo" src="https://elevenfifty.org/wp-content/uploads/2019/03/mobile-shield.png" />
                </a>
                @Html.ActionLink("A Poll Poll".ToUpper(), "Index", "Home", new { area = "" }, new { @class = "navbar-brand" })
            </div>
            <div class="navbar-collapse collapse">
                <ul class="nav navbar-nav">
                    <li>@Html.ActionLink("Questions", "Index", "Question")</li>
                </ul>
                @Html.Partial("_LoginPartial")
            </div>
        </div>
    </div>
    <div class="container body-content" style="display: flex; flex-direction: column; min-height: 100%;">
        @RenderBody()
        <div class="flex-filler"></div>
        <footer>
            <p>#APP @DateTime.Now.Year</p>
        </footer>
    </div>

    @Scripts.Render("~/bundles/jquery")
    @Scripts.Render("~/bundles/bootstrap")
    @RenderSection("scripts", required: false)
</body>
</html>